# Generated by Django 5.0.6 on 2024-08-04 10:20

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('RouteId', models.IntegerField(primary_key=True, serialize=False)),
                ('ArrivalTime', models.TimeField()),
                ('DepartureTime', models.TimeField()),
                ('Distance', models.IntegerField()),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('StationName', models.CharField(max_length=50)),
                ('StationCode', models.IntegerField(primary_key=True, serialize=False)),
                ('PlatformCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('TrainNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('TrainName', models.CharField(max_length=50)),
                ('CoachCount', models.IntegerField()),
                ('TotalSeats', models.IntegerField()),
                ('AvailableSeats', models.IntegerField()),
                ('Days', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('BookingId', models.IntegerField(primary_key=True, serialize=False)),
                ('BookingDate', models.DateField(auto_now_add=True)),
                ('BookingTime', models.TimeField(auto_now_add=True)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('RouteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.route')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='StationCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.station'),
        ),
        migrations.AddField(
            model_name='route',
            name='TrainNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.train'),
        ),
    ]
