# Generated by Django 5.0.6 on 2024-08-04 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='Distance',
        ),
    ]
